import {MODULES,PROJECTS,WHATSAPP_NUMBER,WHATSAPP_DISPLAY,FORM_SCHEMA,WEBCARE_PRICE,CATALOG_REFERENCE} from './config.js';
import {downloadWorkbook} from './excel.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const form=$('#portalForm'); let current=1,acceptedQuote=null,projectCode='',pendingData=null;
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function init(){renderModules();renderMaterials();applyBusinessSchema();bind();updateQuote();showStep(1,false);}
function renderModules(){$('#modulesGrid').innerHTML=MODULES.map(m=>`<label class="module-card"><input type="checkbox" name="modules" value="${esc(m.id)}" data-price="${m.price}"><span class="choice-check"></span><h3>${esc(m.name)}</h3><p>${esc(m.description)}</p><strong>+$${m.price}</strong></label>`).join('');}
function renderMaterials(){$('#materialsChecklist').innerHTML=(FORM_SCHEMA.materiales||[]).map(x=>`<label><input type="checkbox" name="materialChecklist" value="${esc(x)}">${esc(x)}</label>`).join('');}
function bind(){
 form.addEventListener('change',e=>{if(e.target.matches('[name="projectType"],[name="modules"],[name="webcare"],[name="catalogItems"],[name="catalogCategories"]')){updateQuote();if(e.target.name==='projectType')renderContentBuilder();}});
 $$('.next').forEach(b=>b.onclick=()=>next()); $$('.prev').forEach(b=>b.onclick=()=>showStep(current-1));
 $('#quoteAccepted').onchange=e=>$('#acceptQuote').disabled=!e.target.checked;
 $('#acceptQuote').onclick=()=>{acceptedQuote=getQuote();renderContentBuilder();showStep(3)};
 form.onsubmit=prepareSubmit;
 $('#confirmDownload').onclick=finishSubmit; $('.modal-close').onclick=closeModal;
 $('#downloadModal').addEventListener('click',e=>{if(e.target.id==='downloadModal')closeModal();});
}
function getQuote(){const project=form.elements.projectType.value;const p=PROJECTS[project]||{name:'Sin seleccionar',price:0};const modules=$$('[name="modules"]:checked').map(x=>MODULES.find(m=>m.id===x.value)).filter(Boolean);const items=Number(form.elements.catalogItems?.value||0),cats=Number(form.elements.catalogCategories?.value||0);return{projectType:project,projectName:p.name,basePrice:p.price,modules,initialTotal:p.price+modules.reduce((a,m)=>a+m.price,0),webcare:form.elements.webcare.checked,monthlyTotal:form.elements.webcare.checked?WEBCARE_PRICE:0,catalogItems:items,catalogCategories:cats,requiresReview:project==='catalogo'&&(items>Number(CATALOG_REFERENCE.referenciaItems||30)||cats>Number(CATALOG_REFERENCE.referenciaCategorias||5))};}
function updateQuote(){const q=getQuote();$('#liveTotal').textContent=money(q.initialTotal);$('#monthlyTotal').textContent=money(q.monthlyTotal);$('#catalogQuestions').classList.toggle('hidden',q.projectType!=='catalogo');$('#catalogWarning').classList.toggle('hidden',!q.requiresReview);}
function next(){if(current===1&&!form.elements.projectType.value)return alert('Selecciona una arquitectura.');if(current===3&&!validateStep3())return;if(current===1){renderQuote();showStep(2)}else if(current===3){renderFinal();showStep(4)}}
function showStep(n,scroll=true){current=n;$$('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));$('#progressLabel').textContent=`Paso ${n} de 4`;$('#progressBar').style.width=`${n*25}%`;if(scroll){const target=$(`.step[data-step="${n}"]`);requestAnimationFrame(()=>target.scrollIntoView({behavior:'smooth',block:'start'}));}}
function renderQuote(){const q=getQuote();$('#quoteSummary').innerHTML=`<div class="summary-row"><span>Arquitectura</span><strong>${esc(q.projectName)}</strong></div><div class="summary-row"><span>Precio base</span><strong>${money(q.basePrice)}</strong></div>${q.modules.map(m=>`<div class="summary-row"><span>${esc(m.name)}</span><strong>+${money(m.price)}</strong></div>`).join('')}<div class="summary-row summary-total"><span>Total inicial estimado</span><strong>${money(q.initialTotal)}</strong></div><div class="summary-row"><span>ESG WebCare</span><strong>${q.monthlyTotal?money(q.monthlyTotal)+'/mes':'No seleccionado'}</strong></div>`;}
function applyBusinessSchema(){const extras=[];(FORM_SCHEMA.camposNegocio||[]).filter(f=>f.activo!==false).forEach(f=>{const el=form.elements[f.clave];if(el){el.required=!!f.obligatorio;if(f.placeholder)el.placeholder=f.placeholder;}else extras.push(f)});if(extras.length){$('#customFieldsBlock').classList.remove('hidden');$('#customBusinessFields').innerHTML=extras.map(businessFieldHtml).join('')}}
function businessFieldHtml(f){const req=f.obligatorio?' required':'',mark=f.obligatorio?' *':'';if(f.tipo==='textarea')return `<label>${esc(f.etiqueta)}${mark}<textarea name="${esc(f.clave)}"${req} rows="4" placeholder="${esc(f.placeholder||'')}"></textarea></label>`;if(f.tipo==='select')return `<label>${esc(f.etiqueta)}${mark}<select name="${esc(f.clave)}"${req}><option value="">Selecciona</option>${String(f.ayuda||'').split('|').filter(Boolean).map(o=>`<option>${esc(o)}</option>`).join('')}</select></label>`;return `<label>${esc(f.etiqueta)}${mark}<input type="${esc(f.tipo||'text')}" name="${esc(f.clave)}"${req} placeholder="${esc(f.placeholder||'')}"></label>`;}
function fieldHtml(f,attr='data-field'){const req=f.obligatorio?' required':'',mark=f.obligatorio?' *':'',help=f.ayuda?`<small class="helper">${esc(f.ayuda)}</small>`:'';if(f.tipo==='textarea')return `<label>${esc(f.etiqueta)}${mark}<textarea ${attr}="${esc(f.clave)}"${req} rows="3" placeholder="${esc(f.placeholder||'')}"></textarea>${help}</label>`;if(f.tipo==='select')return `<label>${esc(f.etiqueta)}${mark}<select ${attr}="${esc(f.clave)}"${req}><option value="">Selecciona</option>${String(f.ayuda||'').split('|').filter(Boolean).map(o=>`<option>${esc(o)}</option>`).join('')}</select>${help}</label>`;return `<label>${esc(f.etiqueta)}${mark}<input type="${esc(f.tipo||'text')}" ${attr}="${esc(f.clave)}"${req} placeholder="${esc(f.placeholder||'')}">${help}</label>`;}
function renderContentBuilder(){const type=form.elements.projectType.value;if(!type)return;$('#informativeBuilder').classList.toggle('hidden',type!=='informativa');$('#catalogBuilder').classList.toggle('hidden',type!=='catalogo');if(type==='informativa'){ $('#builderTitle').textContent='Fichas de servicios o elementos';$('#builderHelp').textContent='Completa una ficha por servicio. Al final de cada ficha puedes añadir la siguiente o eliminar la actual.';if(!$('#informativeBuilder').children.length)addServiceCard(); } else {$('#builderTitle').textContent='Catálogo organizado por categorías';$('#builderHelp').textContent='Trabaja una categoría completa. Puede contener productos directos o varias subcategorías con productos dentro.';if(!$('#catalogBuilder').children.length)addCategoryCard();}}
function makeFooter(addText,onAdd,removeText,onRemove){const d=document.createElement('div');d.className='item-actions';const add=document.createElement('button');add.type='button';add.className='btn small add-inline';add.textContent=`+ ${addText}`;add.onclick=onAdd;const rem=document.createElement('button');rem.type='button';rem.className='btn small danger';rem.textContent=removeText;rem.onclick=onRemove;d.append(add,rem);return d;}
function confirmRemove(label){return confirm(`¿Deseas eliminar ${label}? Esta acción no se puede deshacer.`)}
function addServiceCard(after=null){const wrap=$('#informativeBuilder'),card=document.createElement('article');card.className='catalog-item service-card';card.innerHTML=`<div class="catalog-item-head"><h4></h4></div><div class="fields two">${(FORM_SCHEMA.camposServicio||FORM_SCHEMA.camposFicha||[]).filter(f=>f.activo!==false).map(f=>fieldHtml(f,'data-service')).join('')}</div>`;card.append(makeFooter('Agregar otro servicio',()=>addServiceCard(card),'Eliminar este servicio',()=>{if(wrap.children.length===1)return alert('Debe existir al menos una ficha.');if(confirmRemove('esta ficha')){card.remove();renumberServices();}}));after?after.after(card):wrap.append(card);renumberServices();requestAnimationFrame(()=>card.scrollIntoView({behavior:'smooth',block:'start'}));}
function renumberServices(){$$('#informativeBuilder .service-card h4').forEach((h,i)=>h.textContent=`Ficha de servicio ${i+1}`)}
function addCategoryCard(after=null){const wrap=$('#catalogBuilder'),cat=document.createElement('article');cat.className='category-card';cat.innerHTML=`<div class="catalog-item-head"><h4></h4></div><div class="fields two">${(FORM_SCHEMA.camposCategoria||[]).filter(f=>f.activo!==false).map(f=>fieldHtml(f,'data-category')).join('')}</div><div class="mode-choice"><p><strong>¿Cómo se organiza esta categoría?</strong></p><label><input type="radio" name="mode-${crypto.randomUUID()}" value="direct" checked> Productos directamente en la categoría</label><label><input type="radio" name="mode-placeholder" value="subcategories"> Tiene una o varias subcategorías</label></div><div class="direct-products"></div><div class="subcategories hidden"></div>`;
 const radios=$$('input[type="radio"]',cat),unique=`mode-${crypto.randomUUID()}`;radios.forEach(r=>r.name=unique);radios.forEach(r=>r.onchange=()=>switchCategoryMode(cat,r.value));
 const direct=$('.direct-products',cat);addProductCard(direct,null,'categoría');
 cat.append(makeFooter('Agregar otra categoría',()=>addCategoryCard(cat),'Eliminar esta categoría',()=>{if(wrap.children.length===1)return alert('Debe existir al menos una categoría.');if(confirmRemove('esta categoría completa')){cat.remove();renumberCategories();}}));
 after?after.after(cat):wrap.append(cat);renumberCategories();requestAnimationFrame(()=>cat.scrollIntoView({behavior:'smooth',block:'start'}));}
function switchCategoryMode(cat,mode){const direct=$('.direct-products',cat),subs=$('.subcategories',cat);direct.classList.toggle('hidden',mode!=='direct');subs.classList.toggle('hidden',mode!=='subcategories');if(mode==='subcategories'&&!subs.children.length)addSubcategoryCard(subs);}
function addSubcategoryCard(container,after=null){const sub=document.createElement('section');sub.className='subcategory-card';sub.innerHTML=`<div class="catalog-item-head"><h5></h5></div><div class="fields two">${(FORM_SCHEMA.camposSubcategoria||[]).filter(f=>f.activo!==false).map(f=>fieldHtml(f,'data-subcategory')).join('')}</div><div class="products-list"></div>`;addProductCard($('.products-list',sub),null,'subcategoría');sub.append(makeFooter('Agregar otra subcategoría',()=>addSubcategoryCard(container,sub),'Eliminar esta subcategoría',()=>{if(container.children.length===1)return alert('Debe existir al menos una subcategoría.');if(confirmRemove('esta subcategoría y sus productos')){sub.remove();renumberSubcategories(container);}}));after?after.after(sub):container.append(sub);renumberSubcategories(container);requestAnimationFrame(()=>sub.scrollIntoView({behavior:'smooth',block:'start'}));}
function renumberSubcategories(container){$$('.subcategory-card> .catalog-item-head h5',container).forEach((h,i)=>h.textContent=`Subcategoría ${i+1}`)}
function addProductCard(container,after=null,scope='categoría'){const product=document.createElement('div');product.className='product-card';product.innerHTML=`<div class="catalog-item-head"><h6></h6></div><div class="fields two">${(FORM_SCHEMA.camposProducto||FORM_SCHEMA.camposFicha||[]).filter(f=>f.activo!==false).map(f=>fieldHtml(f,'data-product')).join('')}</div>`;product.append(makeFooter(`Agregar otro producto a esta ${scope}`,()=>addProductCard(container,product,scope),'Eliminar este producto',()=>{if(container.children.length===1)return alert('Debe existir al menos un producto.');if(confirmRemove('este producto')){product.remove();renumberProducts(container);}}));after?after.after(product):container.append(product);renumberProducts(container);requestAnimationFrame(()=>product.scrollIntoView({behavior:'smooth',block:'start'}));}
function renumberProducts(container){$$(':scope > .product-card > .catalog-item-head h6',container).forEach((h,i)=>h.textContent=`Producto ${i+1}`)}
function renumberCategories(){$$('#catalogBuilder > .category-card > .catalog-item-head h4').forEach((h,i)=>h.textContent=`Categoría ${i+1}`)}
function valuesFrom(el,attr,fields){const out={};(fields||[]).filter(f=>f.activo!==false).forEach(f=>{const input=el.querySelector(`[${attr}="${CSS.escape(f.clave)}"]`);out[f.clave]=input?String(input.value||'').trim():''});return out;}
function collectServices(){return $$('#informativeBuilder .service-card').map((el,i)=>({Orden:i+1,...valuesFrom(el,'data-service',FORM_SCHEMA.camposServicio||FORM_SCHEMA.camposFicha)})).filter(x=>x.name||x.description);}
function collectCatalog(){return $$('#catalogBuilder > .category-card').map((cat,ci)=>{const category=valuesFrom(cat,'data-category',FORM_SCHEMA.camposCategoria),mode=$('input[type="radio"]:checked',cat)?.value||'direct';const result={Orden:ci+1,...category,mode,directProducts:[],subcategories:[]};if(mode==='direct')result.directProducts=$$('.direct-products > .product-card',cat).map((p,pi)=>({Orden:pi+1,...valuesFrom(p,'data-product',FORM_SCHEMA.camposProducto||FORM_SCHEMA.camposFicha)})).filter(x=>x.name||x.description);else result.subcategories=$$('.subcategories > .subcategory-card',cat).map((sub,si)=>({Orden:si+1,...valuesFrom(sub,'data-subcategory',FORM_SCHEMA.camposSubcategoria),products:$$('.products-list > .product-card',sub).map((p,pi)=>({Orden:pi+1,...valuesFrom(p,'data-product',FORM_SCHEMA.camposProducto||FORM_SCHEMA.camposFicha)})).filter(x=>x.name||x.description)}));return result}).filter(x=>x.name||x.directProducts.length||x.subcategories.length);}
function validateStep3(){let ok=true;$$('[data-step="3"] [required]:not(.hidden *)').forEach(el=>{el.classList.remove('error');if(!String(el.value||'').trim()){el.classList.add('error');ok=false;}});const type=form.elements.projectType.value;if(type==='informativa'&&!collectServices().length){alert('Completa al menos una ficha de servicio.');ok=false;}if(type==='catalogo'){const cats=collectCatalog();if(!cats.length){alert('Completa al menos una categoría.');ok=false;}for(const c of cats){if(c.mode==='direct'&&!c.directProducts.length){alert(`La categoría “${c.name||'sin nombre'}” necesita al menos un producto.`);ok=false;break;}if(c.mode==='subcategories'&&c.subcategories.some(s=>!s.products.length)){alert(`Cada subcategoría de “${c.name||'la categoría'}” necesita al menos un producto.`);ok=false;break;}}}if(!ok)alert('Revisa los campos obligatorios marcados.');return ok;}
function collectData(){const fd=new FormData(form),quote=acceptedQuote||getQuote();if(!projectCode)projectCode=`ESG-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const business={};(FORM_SCHEMA.camposNegocio||[]).filter(f=>f.activo!==false).forEach(f=>business[f.clave]=fd.get(f.clave)||'');return{projectCode,submittedAt:new Date().toISOString(),quote,business,services:quote.projectType==='informativa'?collectServices():[],categories:quote.projectType==='catalogo'?collectCatalog():[],materials:fd.getAll('materialChecklist')};}
function countProducts(data){return data.quote.projectType==='informativa'?data.services.length:data.categories.reduce((n,c)=>n+c.directProducts.length+c.subcategories.reduce((a,s)=>a+s.products.length,0),0)}
function renderFinal(){const d=collectData(),count=countProducts(d);$('#finalSummary').innerHTML=`<div class="summary-row"><span>Cliente</span><strong>${esc(d.business.clientName)}</strong></div><div class="summary-row"><span>Negocio</span><strong>${esc(d.business.businessName)}</strong></div><div class="summary-row"><span>Arquitectura</span><strong>${esc(d.quote.projectName)}</strong></div><div class="summary-row"><span>${d.quote.projectType==='catalogo'?'Categorías':'Fichas'}</span><strong>${d.quote.projectType==='catalogo'?d.categories.length:d.services.length}</strong></div><div class="summary-row"><span>Productos / elementos</span><strong>${count}</strong></div><div class="summary-row"><span>Estimado inicial</span><strong>${money(d.quote.initialTotal)}</strong></div>`;}
function prepareSubmit(e){e.preventDefault();if(!$('#dataConsent').checked)return alert('Confirma la autorización para continuar.');pendingData=collectData();$('#downloadModal').classList.remove('hidden');document.body.classList.add('modal-open');$('#confirmDownload').focus();}
function closeModal(){$('#downloadModal').classList.add('hidden');document.body.classList.remove('modal-open');}
function finishSubmit(){if(!pendingData)return;const data=pendingData;closeModal();const btn=$('#submitBtn');btn.disabled=true;btn.textContent='Generando Excel maestro...';downloadWorkbook(data);const count=countProducts(data);const text=`Hola, ESG Experience.\n\nHe completado el Formulario Maestro de mi proyecto web.\n\nCódigo: ${data.projectCode}\nCliente: ${data.business.clientName}\nNegocio: ${data.business.businessName}\nArquitectura: ${data.quote.projectName}\n${data.quote.projectType==='catalogo'?`Categorías: ${data.categories.length}\nProductos: ${count}`:`Fichas registradas: ${data.services.length}`}\nEstimado inicial: ${money(data.quote.initialTotal)}\n\nAdjunto manualmente en este chat:\n1. El Excel maestro descargado.\n2. El logo oficial.\n3. Las fotografías originales identificadas con los nombres escritos en el Excel.\n4. Lista de precios, catálogos, PDFs o documentos oficiales vigentes.\n5. Links o imágenes de páginas de referencia.\n6. Manual de marca, testimonios, videos, políticas y cualquier material adicional disponible.\n\nPor favor, revisen el Excel y los archivos para confirmar el alcance final.`;const url=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;window.open(url,'_blank','noopener,noreferrer')||(location.href=url);$('#submitMessage').className='notice success-message';$('#submitMessage').innerHTML=`<strong>Excel maestro descargado.</strong><br>Busca el archivo en Descargas y adjúntalo en WhatsApp junto con los materiales. Código: <strong>${esc(data.projectCode)}</strong> · ${esc(WHATSAPP_DISPLAY)}`;btn.disabled=false;btn.textContent='Abrir WhatsApp otra vez';btn.onclick=()=>window.open(url,'_blank','noopener,noreferrer');}
init();
