import {MODULES,PROJECTS,WHATSAPP_NUMBER,WHATSAPP_DISPLAY} from './config.js';
import {downloadWorkbook} from './excel.js';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const form=$('#portalForm');let current=1,acceptedQuote=null,projectCode='';
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n||0);
function init(){renderModules();bind();addOffering();updateQuote();showStep(1);}
function renderModules(){$('#modulesGrid').innerHTML=MODULES.map(m=>`<label class="module-card"><input type="checkbox" name="modules" value="${m.id}" data-price="${m.price}"><span class="choice-check"></span><h3>${m.name}</h3><p>${m.description}</p><strong>+$${m.price}</strong></label>`).join('');}
function bind(){form.addEventListener('change',e=>{if(e.target.matches('[name="projectType"],[name="modules"],[name="webcare"],[name="catalogItems"],[name="catalogCategories"]'))updateQuote();});$$('.next').forEach(b=>b.onclick=()=>next());$$('.prev').forEach(b=>b.onclick=()=>showStep(current-1));$('#quoteAccepted').onchange=e=>$('#acceptQuote').disabled=!e.target.checked;$('#acceptQuote').onclick=()=>{acceptedQuote=getQuote();showStep(3)};$('#addCatalogItem').onclick=addOffering;form.onsubmit=submitForm;}
function getQuote(){const project=form.elements.projectType.value;const p=PROJECTS[project]||{name:'Sin seleccionar',price:0};const modules=$$('[name="modules"]:checked').map(x=>MODULES.find(m=>m.id===x.value)).filter(Boolean);const items=Number(form.elements.catalogItems?.value||0),cats=Number(form.elements.catalogCategories?.value||0);return{projectType:project,projectName:p.name,basePrice:p.price,modules,initialTotal:p.price+modules.reduce((a,m)=>a+m.price,0),webcare:form.elements.webcare.checked,monthlyTotal:form.elements.webcare.checked?25:0,catalogItems:items,catalogCategories:cats,requiresReview:project==='catalogo'&&(items>30||cats>5)};}
function updateQuote(){const q=getQuote();$('#liveTotal').textContent=money(q.initialTotal);$('#monthlyTotal').textContent=money(q.monthlyTotal);$('#catalogQuestions').classList.toggle('hidden',q.projectType!=='catalogo');$('#catalogWarning').classList.toggle('hidden',!q.requiresReview);}
function next(){if(current===1&&!form.elements.projectType.value)return alert('Selecciona una arquitectura.');if(current===3&&!validateStep3())return; if(current===1){renderQuote();showStep(2)}else if(current===3){renderFinal();showStep(4)}}
function showStep(n){current=n;$$('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));$('#progressLabel').textContent=`Paso ${n} de 4`;$('#progressBar').style.width=`${n*25}%`;scrollTo({top:0,behavior:'smooth'});}
function renderQuote(){const q=getQuote();$('#quoteSummary').innerHTML=`<div class="summary-row"><span>Arquitectura</span><strong>${q.projectName}</strong></div><div class="summary-row"><span>Precio base</span><strong>${money(q.basePrice)}</strong></div>${q.modules.map(m=>`<div class="summary-row"><span>${m.name}</span><strong>+${money(m.price)}</strong></div>`).join('')}<div class="summary-row summary-total"><span>Total inicial estimado</span><strong>${money(q.initialTotal)}</strong></div><div class="summary-row"><span>ESG WebCare</span><strong>${q.monthlyTotal?money(q.monthlyTotal)+'/mes':'No seleccionado'}</strong></div>`;}
function validateStep3(){let ok=true;$$('[data-step="3"] [required]').forEach(el=>{el.classList.remove('error');if(!String(el.value||'').trim()){el.classList.add('error');ok=false;}});if(!collectOfferings().length){alert('Agrega al menos una ficha de servicio o producto.');ok=false;}if(!ok)alert('Completa los campos obligatorios marcados.');return ok;}
function addOffering(){const i=$$('#catalogItems .catalog-item').length+1,div=document.createElement('div');div.className='catalog-item';div.innerHTML=`<div class="catalog-item-head"><h4>Ficha ${i}</h4><button type="button" class="remove-item">Eliminar</button></div><div class="fields two">
<label>Código interno (opcional)<input data-cat="code" placeholder="Ej. LED-040"></label><label>Estado<select data-cat="status"><option>Activo</option><option>Próximamente</option><option>Oculto</option></select></label>
<label>Categoría *<input data-cat="category" required placeholder="Ej. Pantallas interiores"></label><label>Subcategoría<input data-cat="subcategory" placeholder="Ej. Residencial"></label>
<label>Título oficial *<input data-cat="name" required placeholder="Ej. Pantalla LED de 40 pulgadas"></label><label>Precio o desde<input data-cat="price" placeholder="Ej. Desde $499 / Cotización"></label>
<label>Variantes, colores o modelos<input data-cat="variants" placeholder="Ej. 40, 50 y 60 pulgadas"></label><label>¿Destacado?<select data-cat="featured"><option>No</option><option>Sí</option></select></label></div>
<label>Descripción completa *<textarea data-cat="description" required rows="4" placeholder="Qué es, para quién es, beneficios y características principales."></textarea></label>
<label>Qué incluye<textarea data-cat="includes" rows="3" placeholder="Instalación, soporte, montaje, accesorios, garantía..."></textarea></label>
<div class="fields two"><label>Especificaciones, medidas o duración<textarea data-cat="specs" rows="3"></textarea></label><label>Condiciones importantes<textarea data-cat="conditions" rows="3"></textarea></label></div>
<div class="fields two"><label>Garantía<input data-cat="warranty"></label><label>Tiempo de entrega o instalación<input data-cat="delivery"></label><label>Palabras clave<input data-cat="keywords" placeholder="Separadas por comas"></label><label>Llamada a la acción<input data-cat="cta" placeholder="Ej. Solicitar cotización"></label></div>
<label>Nombres exactos de las fotos que enviarás<textarea data-cat="images" rows="3" placeholder="Una por línea: LED-40-frontal.jpg&#10;LED-40-lateral.jpg"></textarea></label><label>Observaciones para ESG<textarea data-cat="notes" rows="3" placeholder="Información interna, prioridades o aclaraciones."></textarea></label>`;div.querySelector('.remove-item').onclick=()=>{if($$('#catalogItems .catalog-item').length>1){div.remove();renumber();}};$('#catalogItems').append(div);}
function renumber(){$$('#catalogItems .catalog-item h4').forEach((h,i)=>h.textContent=`Ficha ${i+1}`)}
function collectOfferings(){return $$('#catalogItems .catalog-item').map((el,idx)=>({Orden:idx+1,Código:el.querySelector('[data-cat="code"]').value.trim(),Categoría:el.querySelector('[data-cat="category"]').value.trim(),Subcategoría:el.querySelector('[data-cat="subcategory"]').value.trim(),Nombre:el.querySelector('[data-cat="name"]').value.trim(),Precio:el.querySelector('[data-cat="price"]').value.trim(),Variantes:el.querySelector('[data-cat="variants"]').value.trim(),Imágenes:el.querySelector('[data-cat="images"]').value.trim(),Destacado:el.querySelector('[data-cat="featured"]').value,Estado:el.querySelector('[data-cat="status"]').value,Descripción:el.querySelector('[data-cat="description"]').value.trim(),Incluye:el.querySelector('[data-cat="includes"]').value.trim(),Especificaciones:el.querySelector('[data-cat="specs"]').value.trim(),Condiciones:el.querySelector('[data-cat="conditions"]').value.trim(),Garantía:el.querySelector('[data-cat="warranty"]').value.trim(),Entrega:el.querySelector('[data-cat="delivery"]').value.trim(),Palabras_clave:el.querySelector('[data-cat="keywords"]').value.trim(),CTA:el.querySelector('[data-cat="cta"]').value.trim(),Observaciones_ESG:el.querySelector('[data-cat="notes"]').value.trim()})).filter(x=>x.Nombre||x.Descripción);}
function collectData(){const fd=new FormData(form),quote=acceptedQuote||getQuote();if(!projectCode)projectCode=`ESG-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const fields=['clientName','clientEmail','clientPhone','publicWhatsapp','businessName','tagline','businessType','currency','city','serviceArea','businessDescription','websiteGoal','aboutText','differentiators','instagram','facebook','tiktok','whatsappChannel','currentWebsite','publicEmail','address','hours','hasLogo','logoFileName','brandColors','brandFonts','desiredStyle','avoidStyle','references','heroTitle','heroText','heroButton','heroButtonDestination','promoBanner','promoButton','promoDestination','catalogItemLabel','testimonials','faq','policies','paymentMethods','financing','deliveryTime','languages','materialsNotes'];const business={};fields.forEach(k=>business[k]=fd.get(k)||'');return{projectCode,submittedAt:new Date().toISOString(),quote,business,items:collectOfferings(),materials:fd.getAll('materialChecklist')};}
function renderFinal(){const d=collectData();$('#finalSummary').innerHTML=`<div class="summary-row"><span>Cliente</span><strong>${d.business.clientName}</strong></div><div class="summary-row"><span>Negocio</span><strong>${d.business.businessName}</strong></div><div class="summary-row"><span>Arquitectura</span><strong>${d.quote.projectName}</strong></div><div class="summary-row"><span>Fichas completas</span><strong>${d.items.length}</strong></div><div class="summary-row"><span>Estimado inicial</span><strong>${money(d.quote.initialTotal)}</strong></div>`;}
function submitForm(e){e.preventDefault();if(!$('#dataConsent').checked)return alert('Confirma la autorización para continuar.');const btn=$('#submitBtn');btn.disabled=true;btn.textContent='Generando Excel maestro...';const data=collectData();downloadWorkbook(data);const text=`Hola, ESG Experience.\n\nHe completado el Formulario Maestro de mi proyecto web.\n\nCódigo: ${data.projectCode}\nCliente: ${data.business.clientName}\nNegocio: ${data.business.businessName}\nArquitectura: ${data.quote.projectName}\nFichas registradas: ${data.items.length}\nEstimado inicial: ${money(data.quote.initialTotal)}\n\nAdjunto en este chat:\n1. El Excel maestro descargado por el portal.\n2. El logo oficial en su mejor calidad.\n3. Las fotos originales identificadas con los nombres escritos en cada ficha.\n4. Lista de precios, catálogos, PDFs o documentos oficiales vigentes.\n5. Links o imágenes de páginas de referencia.\n6. Manual de marca, testimonios, videos, políticas y cualquier material adicional disponible.\n\nPor favor, revisen el Excel y los archivos para confirmar el alcance final.`;const url=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`;window.open(url,'_blank','noopener,noreferrer')|| (location.href=url);$('#submitMessage').className='notice success-message';$('#submitMessage').innerHTML=`<strong>Excel maestro descargado.</strong><br>Adjúntalo en WhatsApp junto con logo, fotos identificadas, documentos oficiales y referencias. Código: <strong>${data.projectCode}</strong> · ${WHATSAPP_DISPLAY}`;btn.disabled=false;btn.textContent='Abrir WhatsApp otra vez';btn.onclick=()=>window.open(url,'_blank','noopener,noreferrer');}
init();
